on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  jobs:
    docker:
      steps:
        # need checkout before using compose-action
        - uses: actions/checkout@v3
        - uses: isbang/compose-action@v1.2.0
          with:
            compose-file: "./docker-compose.yaml"
            down-flags: "--volumes"
