  docker:
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
          api
          front