# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  api:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: api # Here the path to the folder where package-lock.json is located.

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test 
    # -
    #   name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    # -
    #   name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mietke/demo-app:latest
  front:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: myblog # Here the path to the folder where package-lock.json is located.

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: myblog/package-lock.json
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
#
